// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ExecuteCommand(arg1:string,arg2:Record<string, any>):Promise<string>;

export function ExportTemplateToFile(arg1:models.TemplateFile,arg2:string):Promise<void>;

export function GenerateYAMLFromTemplate(arg1:models.TemplateFile):Promise<string>;

export function GetCommandText(arg1:string,arg2:Record<string, any>):Promise<string>;

export function ImportTemplate():Promise<models.TemplateFile>;

export function ImportTemplateFromURL(arg1:string):Promise<models.TemplateFile>;

export function OpenFileDialog():Promise<string>;

export function ParseCommandToTemplate(arg1:string):Promise<models.TemplateFile>;

export function SaveFileDialog():Promise<string>;

export function SaveYAMLToFile(arg1:string):Promise<void>;

export function ValidateYAMLTemplate(arg1:string):Promise<void>;
