// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteCommand(arg1:string,arg2:Record<string, any>):Promise<string>;

export function GetCommandText(arg1:string,arg2:Record<string, any>):Promise<string>;

export function ImportTemplate():Promise<main.TemplateFile>;

export function ImportTemplateFromURL(arg1:string):Promise<main.TemplateFile>;

export function OpenFileDialog():Promise<string>;

export function SaveFileDialog():Promise<string>;
