// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExportTemplateToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportTemplateToFile'](arg1, arg2);
}

export function GenerateYAMLFromTemplate(arg1) {
  return window['go']['main']['App']['GenerateYAMLFromTemplate'](arg1);
}

export function GetCommandText(arg1, arg2) {
  return window['go']['main']['App']['GetCommandText'](arg1, arg2);
}

export function ImportTemplate() {
  return window['go']['main']['App']['ImportTemplate']();
}

export function ImportTemplateFromURL(arg1) {
  return window['go']['main']['App']['ImportTemplateFromURL'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ParseCommandToTemplate(arg1) {
  return window['go']['main']['App']['ParseCommandToTemplate'](arg1);
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function SaveYAMLToFile(arg1) {
  return window['go']['main']['App']['SaveYAMLToFile'](arg1);
}

export function ValidateYAMLTemplate(arg1) {
  return window['go']['main']['App']['ValidateYAMLTemplate'](arg1);
}
