/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CommandExecutor: typeof import('./src/components/CommandExecutor.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    DynamicCommandForm: typeof import('./src/components/DynamicCommandForm.vue')['default']
    FavoriteTemplateSelector: typeof import('./src/components/FavoriteTemplateSelector.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Select: typeof import('primevue/select')['default']
    TemplateEditorModal: typeof import('./src/components/TemplateEditorModal.vue')['default']
    TemplateMetadataDisplay: typeof import('./src/components/TemplateMetadataDisplay.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
