// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';
import {frontend} from '../models';

export function DeleteFavTemplate(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:Record<string, any>):Promise<string>;

export function ExportTemplateToFile(arg1:models.TemplateFile,arg2:string):Promise<void>;

export function GenerateYAMLFromTemplate(arg1:models.TemplateFile):Promise<string>;

export function GetAppSettings():Promise<config.AppSettings>;

export function GetCommandText(arg1:string,arg2:Record<string, any>):Promise<string>;

export function GetFavTemplate(arg1:string):Promise<models.TemplateFile>;

export function ImportTemplate():Promise<models.TemplateFile>;

export function ImportTemplateFromURL(arg1:string):Promise<models.TemplateFile>;

export function ListFavTemplates():Promise<Array<models.TemplateFile>>;

export function OpenFileDialog():Promise<string>;

export function OpenFileDialogWithFilters(arg1:Array<frontend.FileFilter>):Promise<string>;

export function ParseCommandToTemplate(arg1:string):Promise<models.TemplateFile>;

export function ParseYAMLToTemplate(arg1:string):Promise<models.TemplateFile>;

export function SaveFavTemplate(arg1:models.TemplateFile):Promise<void>;

export function SaveFileDialog():Promise<string>;

export function SaveYAMLToFile(arg1:string):Promise<void>;

export function UpdateAppSettings(arg1:Record<string, any>):Promise<void>;

export function UpdateFavTemplate(arg1:string,arg2:string,arg3:models.TemplateFile):Promise<void>;

export function ValidateYAMLTemplate(arg1:string):Promise<void>;
